
#   HUOM!!!! PVPRange1 koordinaatit on oltava suurempia kuin PVPRange2:ssa jos ei ole se laittaa pvpn pelaajille 
#   pvp alueen ulko puolella !!!HUOM
PVPRange1:
    X: 100
    Z: 100
PVPRange2:
    X: -100
    Z: -100